# Generated by Django 3.2.3 on 2022-08-15 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulado', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questao',
            options={'verbose_name_plural': 'Questões'},
        ),
        migrations.AddField(
            model_name='questao',
            name='simulado',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='simulado.simulado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resposta',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulado.questao'),
        ),
    ]
