# Generated by Django 3.2.3 on 2022-08-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulado', '0003_auto_20220815_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
