# Generated by Django 4.1 on 2022-08-26 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulado', '0006_auto_20220817_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulado.questao')),
            ],
        ),
    ]
