# Generated by Django 4.1 on 2022-08-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulado', '0007_alternativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='texto',
            field=models.TextField(verbose_name='texto'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='texto',
            field=models.TextField(verbose_name='texto'),
        ),
        migrations.AlterField(
            model_name='simulado',
            name='titulo',
            field=models.CharField(max_length=20, verbose_name='titulo'),
        ),
    ]
