# Generated by Django 4.1 on 2022-08-26 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulado', '0008_alter_alternativa_texto_alter_questao_texto_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='alternativa',
            new_name='Alternativa_questao',
        ),
    ]
