# Generated by Django 4.1 on 2022-08-26 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulado', '0010_rename_alternativa_questao_alternativa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alternativa',
            new_name='AlternativaQ',
        ),
    ]
