# Generated by Django 4.1 on 2022-08-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulado', '0011_rename_alternativa_alternativaq'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativaq',
            name='correta',
            field=models.BooleanField(default=False),
        ),
    ]
