# Generated by Django 4.1 on 2022-08-26 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulado', '0013_altquestão_alter_questao_texto_alter_resposta_texto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='texto')),
                ('correta', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='questao',
            name='texto',
            field=models.TextField(verbose_name='texto'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='texto',
            field=models.TextField(verbose_name='texto'),
        ),
        migrations.DeleteModel(
            name='AltQuestão',
        ),
        migrations.AddField(
            model_name='alternativa',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulado.questao'),
        ),
    ]
