# Generated by Django 4.1 on 2022-08-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulado', '0015_questao_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulado',
            name='pontuacao',
            field=models.IntegerField(default=0),
        ),
    ]
