# Generated by Django 4.1 on 2022-09-01 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulado', '0016_simulado_pontuacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='questao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='simulado.questao'),
        ),
    ]
