# Generated by Django 3.2.3 on 2022-07-25 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dayleSchedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cronograma',
            old_name='privacidade',
            new_name='privado',
        ),
    ]
