# Generated by Django 3.2.3 on 2022-07-25 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dayleSchedule', '0002_rename_privacidade_cronograma_privado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cronograma',
            old_name='privado',
            new_name='privacidade',
        ),
    ]
