# Generated by Django 3.2.3 on 2022-07-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayleSchedule', '0003_rename_privado_cronograma_privacidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cronograma',
            old_name='nome',
            new_name='titulo',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='assunto',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='tipo',
            field=models.CharField(default='Sem tipo', max_length=10),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='titulo',
            field=models.CharField(default='Novo Cronograma', max_length=50),
        ),
    ]
