# Generated by Django 3.2.3 on 2022-07-29 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dayleSchedule', '0004_auto_20220729_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cronograma',
            old_name='titulo',
            new_name='nome',
        ),
    ]
