# Generated by Django 3.2.3 on 2022-07-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayleSchedule', '0006_cronograma_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronograma',
            name='nome',
            field=models.CharField(default='Sem Nome', max_length=100),
        ),
    ]
