# Generated by Django 3.2.3 on 2022-07-29 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dayleSchedule', '0007_alter_cronograma_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronograma',
            name='nome',
        ),
    ]
