# Generated by Django 3.2.3 on 2022-07-30 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dayleSchedule', '0009_alter_tarefa_titulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cronograma',
            options={'verbose_name': 'Cronograma'},
        ),
    ]
