# Generated by Django 3.2.3 on 2022-07-31 00:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dayleSchedule', '0010_alter_cronograma_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronograma',
            name='data',
        ),
        migrations.AddField(
            model_name='cronograma',
            name='data_fim',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data fim Cronograma'),
        ),
        migrations.AddField(
            model_name='cronograma',
            name='data_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data inicio Cronograma'),
        ),
    ]
