# Generated by Django 3.2.3 on 2022-07-31 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dayleSchedule', '0011_auto_20220731_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='hora_fim',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='hora_inicio',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
